name: Interpreter General Pipeline

on: [push, pull_request]

jobs:
  build:
    if:  github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: github
          settings-path: ${{ github.workspace }}
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Publish on Github Packages
        run: ./gradlew publish
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: "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"
        
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Google Java Format
        uses: axel-op/googlejavaformat-action@v3.4.0
        with:
          # Arguments for the Google Java Format executable
          args: --skip-sorting-imports
            
